---
- name: Create deployment user
  user:
    name: deploy
    groups:
      - sudo

- name: Add authorized key for deployment user
  authorized_key:
    user: deploy
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Create deployment directories
  become: yes
  file:
    path: /var/www/
    state: directory
    owner: deploy
    group: deploy

- name: Install Bundler
  become: yes
  gem:
    name: bundler
    user_install: no

- name: Create service definition
  become: yes
  copy:
    dest: "/etc/systemd/system/librariesio.service"
    src: "librariesio.service"

- name: Enable librariesio service
  become: yes
  systemd:
    name: librariesio
    enabled: yes
    state: started
    daemon_reload: yes

- name: Hourly restart cron job
  cron: name="restart libraries" minute="{{ 59 | random(seed=inventory_hostname) }}" job="/sbin/restart librariesio > /dev/null 2>&1"
